contrib/struts-faces/src/example/org/apache/struts/webapp/example/LogonAction.java
/*
 * Copyright 1999-2001,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.apache.struts.webapp.example;


import java.util.Locale;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpServletResponse;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import org.apache.struts.util.MessageResources;
import org.apache.struts.util.ModuleException;
import org.apache.commons.beanutils.PropertyUtils;


/**
 * Implementation of <strong>Action</strong> that validates a user logon.
 *
 * @author Craig R. McClanahan
 * @version $Revision: 1.3 $ $Date: 2004/03/08 02:49:52 $
 */

public final class LogonAction extends Action {


    // ----------------------------------------------------- Instance Variables


    /**
     * The <code>Log</code> instance for this application.
     */
    private Log log =
        LogFactory.getLog("org.apache.struts.webapp.Example");


    // --------------------------------------------------------- Public Methods


    /**
     * Process the specified HTTP request, and create the corresponding HTTP
     * response (or forward to another web component that will create it).
     * Return an <code>ActionForward</code> instance describing where and how
     * control should be forwarded, or <code>null</code> if the response has
     * already been completed.
     *
     * @param mapping The ActionMapping used to select this instance
     * @param actionForm The optional ActionForm bean for this request (if any)
     * @param request The HTTP request we are processing
     * @param response The HTTP response we are creating
     *
     * @exception Exception if business logic throws an exception
     */
    public ActionForward execute(ActionMapping mapping,
				 ActionForm form,
				 HttpServletRequest request,
				 HttpServletResponse response)
	throws Exception {

	// Extract attributes we will need
	Locale locale = getLocale(request);
	MessageResources messages = getResources(request);
	User user = null;

	// Validate the request parameters specified by the user
	ActionErrors errors = new ActionErrors();
	String username = (String)
            PropertyUtils.getSimpleProperty(form, "username");
        String password = (String)
            PropertyUtils.getSimpleProperty(form, "password");
	UserDatabase database = (UserDatabase)
	  servlet.getServletContext().getAttribute(Constants.DATABASE_KEY);
	if (database == null)
            errors.add(ActionErrors.GLOBAL_ERROR,
                       new ActionError("error.database.missing"));
	else {
	    user = getUser(database, username);
	    if ((user != null) && !user.getPassword().equals(password))
		user = null;
	    if (user == null)
                errors.add(ActionErrors.GLOBAL_ERROR,
                           new ActionError("error.password.mismatch"));
	}

	// Report any errors we have discovered back to the original form
	if (!errors.isEmpty()) {
	    saveErrors(request, errors);
            return (mapping.getInputForward());
	}

	// Save our logged-in user in the session
	HttpSession session = request.getSession();
	session.setAttribute(Constants.USER_KEY, user);
        if (log.isDebugEnabled()) {
            log.debug("LogonAction: User '" + user.getUsername() +
                      "' logged on in session " + session.getId());
        }

        // Remove the obsolete form bean
	if (mapping.getAttribute() != null) {
            if ("request".equals(mapping.getScope()))
                request.removeAttribute(mapping.getAttribute());
            else
                session.removeAttribute(mapping.getAttribute());
        }

	// Forward control to the specified success URI
	return (mapping.findForward("success"));

    }


    // ------------------------------------------------------ Protected Methods


    /**
     * Look up the user, throwing an exception to simulate business logic
     * rule exceptions.
     *
     * @param database Database in which to look up the user
     * @param username Username specified on the logon form
     *
     * @exception AppException if a business logic rule is violated
     */
    public User getUser(UserDatabase database, String username)
        throws ModuleException {

        // Force an ArithmeticException which can be handled explicitly
        if ("arithmetic".equals(username)) {
            throw new ArithmeticException();
        }

        // Force an application-specific exception which can be handled
        if ("expired".equals(username)) {
            throw new ExpiredPasswordException(username);
        }

        // Look up and return the specified user
        return ((User) database.findUser(username));

    }


}

contrib/struts-faces/src/example2/org/apache/struts/webapp/example2/LogonAction.java
/*
 * Copyright 1999-2001,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.apache.struts.webapp.example2;


import java.util.Locale;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.commons.beanutils.PropertyUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.util.MessageResources;
import org.apache.struts.util.ModuleException;


/**
 * Implementation of <strong>Action</strong> that validates a user logon.
 *
 * @author Craig R. McClanahan
 * @version $Revision: 1.3 $ $Date: 2004/04/29 03:58:40 $
 */

public final class LogonAction extends Action {


    // ----------------------------------------------------- Instance Variables


    /**
     * The <code>Log</code> instance for this application.
     */
    private Log log =
        LogFactory.getLog("org.apache.struts.webapp.Example");


    // --------------------------------------------------------- Public Methods


    /**
     * Process the specified HTTP request, and create the corresponding HTTP
     * response (or forward to another web component that will create it).
     * Return an <code>ActionForward</code> instance describing where and how
     * control should be forwarded, or <code>null</code> if the response has
     * already been completed.
     *
     * @param mapping The ActionMapping used to select this instance
     * @param actionForm The optional ActionForm bean for this request (if any)
     * @param request The HTTP request we are processing
     * @param response The HTTP response we are creating
     *
     * @exception Exception if business logic throws an exception
     */
    public ActionForward execute(ActionMapping mapping,
				 ActionForm form,
				 HttpServletRequest request,
				 HttpServletResponse response)
	throws Exception {

	// Extract attributes we will need
	Locale locale = getLocale(request);
	MessageResources messages = getResources(request);
	User user = null;

	// Validate the request parameters specified by the user
	ActionErrors errors = new ActionErrors();
	String username = (String)
            PropertyUtils.getSimpleProperty(form, "username");
        String password = (String)
            PropertyUtils.getSimpleProperty(form, "password");
	UserDatabase database = (UserDatabase)
	  servlet.getServletContext().getAttribute(Constants.DATABASE_KEY);
	if (database == null)
            errors.add(ActionErrors.GLOBAL_ERROR,
                       new ActionError("error.database.missing"));
	else {
	    user = getUser(database, username);
	    if ((user != null) && !user.getPassword().equals(password))
		user = null;
	    if (user == null)
                errors.add(ActionErrors.GLOBAL_ERROR,
                           new ActionError("error.password.mismatch"));
	}

	// Report any errors we have discovered back to the original form
	if (!errors.isEmpty()) {
	    saveErrors(request, errors);
            return (mapping.getInputForward());
	}

	// Save our logged-in user in the session
	HttpSession session = request.getSession();
	session.setAttribute(Constants.USER_KEY, user);
        if (log.isDebugEnabled()) {
            log.debug("LogonAction: User '" + user.getUsername() +
                      "' logged on in session " + session.getId());
        }

        // Remove the obsolete form bean
	if (mapping.getAttribute() != null) {
            if ("request".equals(mapping.getScope()))
                request.removeAttribute(mapping.getAttribute());
            else
                session.removeAttribute(mapping.getAttribute());
        }

	// Forward control to the specified success URI
	return (mapping.findForward("success"));

    }


    // ------------------------------------------------------ Protected Methods


    /**
     * Look up the user, throwing an exception to simulate business logic
     * rule exceptions.
     *
     * @param database Database in which to look up the user
     * @param username Username specified on the logon form
     *
     * @exception AppException if a business logic rule is violated
     */
    public User getUser(UserDatabase database, String username)
        throws ModuleException {

        // Force an ArithmeticException which can be handled explicitly
        if ("arithmetic".equals(username)) {
            throw new ArithmeticException();
        }

        // Force an application-specific exception which can be handled
        if ("expired".equals(username)) {
            throw new ExpiredPasswordException(username);
        }

        // Look up and return the specified user
        return ((User) database.findUser(username));

    }


}

contrib/struts-faces/src/systest/org/apache/struts/faces/systest/BindingBean.java
/*
 * Copyright 2002,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.struts.faces.systest;


import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;


/**
 * <p>Bean used to test the <code>binding</code> attribute for
 * selected components.</p>
 */

public class BindingBean {


    private UIComponent write1 = null;
    public UIComponent getWrite1() { return this.write1; }
    public void setWrite1(UIComponent write1) { this.write1 = write1; }


    public String getWrite1ClientId() {
        return write1.getClientId(FacesContext.getCurrentInstance());
    }


}

contrib/struts-faces/src/systest/org/apache/struts/faces/systest/ContextAction.java
/*
 * Copyright 2002,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.struts.faces.systest;

import java.util.Locale;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;


/**
 * <p>Action to render properties from ExternalContext and the corresponding
 * request and application context objects.</p>
 */

public class ContextAction extends Action {


    private static final Log log = LogFactory.getLog(ContextAction.class);


    private String authType = null;
    private String contextPath = null;
    private Locale locale = null;
    private String pathInfo = null;
    private String remoteUser = null;
    private String servletPath = null;


    public String getAuthType() { return (this.authType); }
    public String getContextPath() { return (this.contextPath); }
    public Locale getLocale() { return (this.locale); }
    public String getPathInfo() { return (this.pathInfo); }
    public String getRemoteUser() { return (this.remoteUser); }
    public String getServletPath() { return (this.servletPath); }


    /**
     * <p>Process an attempted logon.</p>
     */
    public ActionForward execute(ActionMapping mapping,
                                 ActionForm form,
                                 HttpServletRequest request,
                                 HttpServletResponse response)
        throws Exception {

        this.authType = request.getAuthType();
        this.contextPath = request.getContextPath();
        this.locale = request.getLocale();
        this.pathInfo = request.getPathInfo();
        this.remoteUser = request.getRemoteUser();
        this.servletPath = request.getServletPath();

        request.setAttribute("contextAction", this);
        return (mapping.findForward("context1"));

    }


}

contrib/struts-faces/src/systest/org/apache/struts/faces/systest/SimpleBean.java
/*
 * Copyright 2002,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.struts.faces.systest;


/**
 * <p>Simple JavaBean for use in managed bean and value binding tests.</p>
 */

public class SimpleBean {


    public String getEternity() {
        return "Eternity";
    }

    public String getSimpleResource() {
        return "resource.simple";
    }

    public String getSimpleContent() {
        return "Retrieved Simple Content";
    }


    public String getFilteredContent() {
        return "Retrieved <b>Filtered</b> Content";
    }


    public String getUnfilteredContent() {
        return "Retrieved <b>Unfiltered</b> Content";
    }


}

contrib/struts-faces/web/systest/context.jsp
<!--

 Copyright 2002,2004 The Apache Software Foundation.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

-->

<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>
<%@ taglib prefix="s" uri="http://struts.apache.org/tags-faces" %>

<f:view>
  <s:html locale="true" xhtml="true">
    <head>
      <title>context</title>
    </head>
    <body>

      <s:form             id="form"
                      action="/context">

      <h:panelGrid   columns="2">

        <%-- ViewRoot Values --%>

        <h:outputText  value="FacesContext.getViewRoot()"/>
        <h:outputText  value="==============================================="/>

        <h:outputText  value="renderKitId"/>
        <h:outputText     id="renderKitIdFC"
                       value="#{facesContext.viewRoot.renderKitId}"/>

        <h:outputText  value="viewId"/>
        <h:outputText     id="viewIdFC"
                       value="#{facesContext.viewRoot.viewId}"/>

        <%-- ExternalContext Values --%>

        <h:outputText  value="ExternalContext"/>
        <h:outputText  value="==============================================="/>

        <h:outputText  value="authType"/>
        <h:outputText     id="authTypeEC"
                       value="#{facesContext.externalContext.authType}"/>

        <h:outputText  value="remoteUser"/>
        <h:outputText     id="remoteUserEC"
                       value="#{facesContext.externalContext.remoteUser}"/>

        <h:outputText  value="requestContextPath"/>
        <h:outputText     id="requestContextPathEC"
                       value="#{facesContext.externalContext.requestContextPath}"/>

        <h:outputText  value="requestLocale"/>
        <h:outputText     id="requestLocaleEC"
                       value="#{facesContext.externalContext.requestLocale}"/>

        <h:outputText  value="requestPathInfo"/>
        <h:outputText     id="requestPathInfoEC"
                       value="#{facesContext.externalContext.requestPathInfo}"/>

        <h:outputText  value="requestServletPath"/>
        <h:outputText     id="requestServletPathEC"
                       value="#{facesContext.externalContext.requestServletPath}"/>

        <%-- Request Values --%>

        <h:outputText  value="HttpServletRequest"/>
        <h:outputText  value="==============================================="/>

        <h:outputText  value="authType"/>
        <h:outputText     id="authTypeRQ"
                       value="#{facesContext.externalContext.request.authType}"/>

        <h:outputText  value="contextPath"/>
        <h:outputText     id="contextPathRQ"
                       value="#{facesContext.externalContext.request.contextPath}"/>

        <h:outputText  value="locale"/>
        <h:outputText     id="localeRQ"
                       value="#{facesContext.externalContext.request.locale}"/>

        <h:outputText  value="pathInfo"/>
        <h:outputText     id="pathInfoRQ"
                       value="#{facesContext.externalContext.request.pathInfo}"/>

        <h:outputText  value="remoteUser"/>
        <h:outputText     id="remoteUserRQ"
                       value="#{facesContext.externalContext.request.remoteUser}"/>

        <h:outputText  value="servletPath"/>
        <h:outputText     id="servletPathRQ"
                       value="#{facesContext.externalContext.request.servletPath}"/>

        <%-- ServletContext Values --%>

        <h:outputText  value="ServletContext"/>
        <h:outputText  value="==============================================="/>

        <h:outputText  value="majorVersion"/>
        <h:outputText     id="majorVersionSC"
                       value="#{facesContext.externalContext.context.majorVersion}"/>

        <h:outputText  value="minorVersion"/>
        <h:outputText     id="minorVersionSC"
                       value="#{facesContext.externalContext.context.minorVersion}"/>

        <h:outputText  value="serverInfo"/>
        <h:outputText     id="serverInfoSC"
                       value="#{facesContext.externalContext.context.serverInfo}"/>

        <h:outputText  value="servletContextName"/>
        <h:outputText     id="servletContextNameSC"
                       value="#{facesContext.externalContext.context.servletContextName}"/>

        <%-- Submit Buttons --%>

        <h:commandButton  id="submit"
                        type="SUBMIT"
                       value="Submit"/>
        <h:commandButton  id="reset"
                        type="RESET"
                       value="Reset"/>

      </h:panelGrid>

      </s:form>

    </body>
  </s:html>
</f:view>

contrib/struts-faces/web/systest/context1.jsp
<!--

 Copyright 2002,2004 The Apache Software Foundation.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

-->

<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>
<%@ taglib prefix="s" uri="http://struts.apache.org/tags-faces" %>

<f:view>
  <s:html locale="true" xhtml="true">
    <head>
      <title>context1</title>
    </head>
    <body>

      <s:form             id="form"
                      action="/context">

      <h:panelGrid   columns="3">

        <%-- ViewRoot Values --%>

        <h:outputText  value="FacesContext.getViewRoot()"/>
        <h:outputText  value="====================================="/>
        <h:outputText  value="====================================="/>

        <h:outputText  value="renderKitId"/>
        <h:outputText     id="renderKitIdFC"
                       value="#{facesContext.viewRoot.renderKitId}"/>
        <h:outputText  value=""/>

        <h:outputText  value="viewId"/>
        <h:outputText     id="viewIdFC"
                       value="#{facesContext.viewRoot.viewId}"/>
        <h:outputText  value=""/>

        <%-- ExternalContext Values --%>

        <h:outputText  value="ExternalContext"/>
        <h:outputText  value="====================================="/>
        <h:outputText  value="====================================="/>

        <h:outputText  value="authType"/>
        <h:outputText     id="authTypeEC"
                       value="#{facesContext.externalContext.authType}"/>
        <h:outputText  value=""/>

        <h:outputText  value="remoteUser"/>
        <h:outputText     id="remoteUserEC"
                       value="#{facesContext.externalContext.remoteUser}"/>
        <h:outputText  value=""/>

        <h:outputText  value="requestContextPath"/>
        <h:outputText     id="requestContextPathEC"
                       value="#{facesContext.externalContext.requestContextPath}"/>
        <h:outputText  value=""/>

        <h:outputText  value="requestLocale"/>
        <h:outputText     id="requestLocaleEC"
                       value="#{facesContext.externalContext.requestLocale}"/>
        <h:outputText  value=""/>

        <h:outputText  value="requestPathInfo"/>
        <h:outputText     id="requestPathInfoEC"
                       value="#{facesContext.externalContext.requestPathInfo}"/>
        <h:outputText  value=""/>

        <h:outputText  value="requestServletPath"/>
        <h:outputText     id="requestServletPathEC"
                       value="#{facesContext.externalContext.requestServletPath}"/>
        <h:outputText  value=""/>

        <%-- Request Values --%>

        <h:outputText  value="HttpServletRequest"/>
        <h:outputText  value="====================================="/>
        <h:outputText  value="====================================="/>

        <h:outputText  value="authType"/>
        <h:outputText     id="authTypeRQ"
                       value="#{facesContext.externalContext.request.authType}"/>
        <h:outputText     id="authTypeCA"
                       value="#{contextAction.authType}"/>

        <h:outputText  value="contextPath"/>
        <h:outputText     id="contextPathRQ"
                       value="#{facesContext.externalContext.request.contextPath}"/>
        <h:outputText     id="contextPathCA"
                       value="#{contextAction.contextPath}"/>

        <h:outputText  value="locale"/>
        <h:outputText     id="localeRQ"
                       value="#{facesContext.externalContext.request.locale}"/>
        <h:outputText     id="localeCA"
                       value="#{contextAction.locale}"/>

        <h:outputText  value="pathInfo"/>
        <h:outputText     id="pathInfoRQ"
                       value="#{facesContext.externalContext.request.pathInfo}"/>
        <h:outputText     id="pathInfoCA"
                       value="#{contextAction.pathInfo}"/>

        <h:outputText  value="remoteUser"/>
        <h:outputText     id="remoteUserRQ"
                       value="#{facesContext.externalContext.request.remoteUser}"/>
        <h:outputText     id="remoteUserCA"
                       value="#{contextAction.remoteUser}"/>

        <h:outputText  value="servletPath"/>
        <h:outputText     id="servletPathRQ"
                       value="#{facesContext.externalContext.request.servletPath}"/>
        <h:outputText     id="servletPathCA"
                       value="#{contextAction.servletPath}"/>

        <%-- ServletContext Values --%>

        <h:outputText  value="ServletContext"/>
        <h:outputText  value="====================================="/>
        <h:outputText  value="====================================="/>

        <h:outputText  value="majorVersion"/>
        <h:outputText     id="majorVersionSC"
                       value="#{facesContext.externalContext.context.majorVersion}"/>
        <h:outputText  value=""/>

        <h:outputText  value="minorVersion"/>
        <h:outputText     id="minorVersionSC"
                       value="#{facesContext.externalContext.context.minorVersion}"/>
        <h:outputText  value=""/>

        <h:outputText  value="serverInfo"/>
        <h:outputText     id="serverInfoSC"
                       value="#{facesContext.externalContext.context.serverInfo}"/>
        <h:outputText  value=""/>

        <h:outputText  value="servletContextName"/>
        <h:outputText     id="servletContextNameSC"
                       value="#{facesContext.externalContext.context.servletContextName}"/>
        <h:outputText  value=""/>

      </h:panelGrid>

      </s:form>

    </body>
  </s:html>
</f:view>

contrib/struts-faces/web/systest/simple.jsp
<!--

 Copyright 2002,2004 The Apache Software Foundation.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

-->

<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>
<%@ taglib prefix="s" uri="http://struts.apache.org/tags-faces" %>

<f:view>
  <s:html locale="true" xhtml="true">
    <head>
      <title>simple</title>
      <s:base/>
      <s:stylesheet path="/stylesheet.css"/>
    </head>
    <body>

      <s:message id="message-direct"
             bundle="messages"
                key="resource.simple"/>
      <s:message id="message-indirect"
             bundle="messages"
              value="#{simple.simpleResource}"/>
      <s:message id="message-filtered"
             bundle="messages"
                key="resource.filtered"/>
      <s:message id="message-unfiltered"
             bundle="messages"
             filter="false"
                key="resource.unfiltered"/>
      <s:message id="message-substitute"
             bundle="messages"
                key="resource.substitute">
        <f:param
              value="Here"/>
        <f:param
              value="#{simple.eternity}"/>
      </s:message>

      <s:loadMessages
           messages="messages"
                var="lookup"/>
      <s:write   id="lookup-simple"
              value="#{lookup['resource.simple']}"/>
      <s:write   id="lookup-filtered"
              value="#{lookup['resource.filtered']}"/>
      <s:write   id="lookup-unfiltered"
             filter="false"
              value="#{lookup['resource.unfiltered']}"/>

      <s:write   id="write-literal"
              value="Literal Write Content"/>
      <s:write   id="write-filtered"
              value="Literal <b>Filtered</b> Content"/>
      <s:write   id="write-unfiltered"
             filter="false"
              value="Literal <b>Unfiltered</b> Content"/>

      <s:write   id="retrieved-literal"
              value="#{simple.simpleContent}"/>
      <s:write   id="retrieved-filtered"
              value="#{simple.filteredContent}"/>
      <s:write   id="retrieved-unfiltered"
             filter="false"
              value="#{simple.unfilteredContent}"/>

      <f:subview id="subview">
        <s:write id="write1"
            binding="#{binding.write1}"
              value="#{binding.write1ClientId}"/>
      </f:subview>

    </body>
  </s:html>
</f:view>